# Generated by Django 3.1.1 on 2020-11-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_blog', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
